{
  "name": "eslint-plugin-try-catch-failsafe",
  "version": "0.1.2",
  "description": "Make sure to use try-catch to wrap up some dangerous actions!",
  "main": "lib/index.js",
  "scripts": {
    "build": "rm -rf lib && swc src -d lib",
    "prepack": "pnpm build",
    "test": "ts-mocha tests/**/*.spec.ts"
  },
  "dependencies": {
    "requireindex": "^1.2.0"
  },
  "devDependencies": {
    "@swc/cli": "^0.1.59",
    "@swc/core": "^1.3.25",
    "@types/eslint": "^8.4.10",
    "@types/estree": "^1.0.0",
    "@types/expect": "^24.3.0",
    "@types/mocha": "^10.0.1",
    "@types/node": "^18.11.18",
    "@types/requireindex": "^1.2.0",
    "eslint": "^8.31.0",
    "mocha": "^10.2.0",
    "ts-mocha": "^10.0.0",
    "typescript": "^4.9.4"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/RexSkz/eslint-plugin-try-catch-failsafe.git"
  },
  "author": "Rex Zeng <rex@rexskz.info>",
  "keywords": [
    "eslint",
    "eslintplugin",
    "eslint-plugin",
    "try-catch",
    "try",
    "catch",
    "failsafe"
  ],
  "license": "MIT"
}
